### ISSUE TITLE
When inside Location tool name is global, should be per user?

### ISSUE THREAD

**Issue by vorburger** [vorburger/minecraft-storeys-maker#118]
The name of the "region" of the new "When inside" Location tool introduced by @edewit in #114 and fixed up in #117 is currently global. If 2 users were to use that Block and both name their Region a "house" then they would get horribly mixed up and confused... It's a little bit similar for the commands already, although this is probably much easier to fix than that (we can't, easily, "namespace" user slash commands, AFAIK).

This is of course an just a multi-user enhancement thought; the new Location tool is really cool!

**Comment by edewit** [comment]
The tool already prefixes the "region" with the user id when it saves the points that the user makes with his axe. So all that would be needed here is for the front-end to know the user GUID.

**Comment by vorburger** [comment]
Right. Actually I think I may have misunderstood #117 ... this:

    String playerBoxLocation = player.getUniqueId() + locationName;

makes it already do the correct thing (above), doesn't it @edewit ? 

> all that would be needed here is for the front-end to know the user GUID.

for... what to work how better? Isn't it already perfectly fine now then? Sorry for my confusion.

So close this, or is there actually anything "to do" ?

**Comment by edewit** [comment]
because the front-end will receive the event that a player has entered named "region" and will execute the blocks accordingly. To differentiate between the region called "house" created by "player 1" and the region called "house" by "player 2" we need to make the front-end aware of the player event prefix namely the player GUID. Does that make sense?

**Comment by vorburger** [comment]
Oh. So right now with #117 merged is it completely broken? :small_airplane: 

Or it works for single user but NOK in case of multi user with regions with same name?

**Comment by edewit** [comment]
it works for single user and multi user as long as they have different region names
