### ISSUE TITLE
JS Release Process?

### ISSUE THREAD

**Issue by vorburger** [vorburger/minecraft-storeys-maker#13]
as discussed in https://github.com/vorburger/minecraft-storeys-maker/pull/4, with the change from the original minecraft.js to a src/index.ts which we build into JS, we'll have to "release" both that JS as well as the matching version of the web-1.0.0-SNAPSHOT-all.jar together somewhere... for me, this is not a high prio while we're still in dev, but let's have this issue to create the neccessary scripting and documentation, when we get to it. I'm personally more interested in a CI/CD to get it all together cloud hosted... ;-)

**Comment by edewit** [comment]
we could use github releases to host our binaries and use [a gradle plugin](https://github.com/riiid/gradle-github-plugin) or something similar to let travis create these releases.

**Comment by vorburger** [comment]
#19 may make this a non-issue - or perhaps for #19 I'll find that we should bundle the JS into the JAR...

**Comment by vorburger** [comment]
@edewit OK for you to close this via #29 ? That works great - I don't see the need to ever do anything else.

**Comment by edewit** [comment]
right, we should then merge the `scratchJSExtensionURL` and the `eventBusURL` into one parameter

**Comment by vorburger** [comment]
> right, we should then merge the scratchJSExtensionURL and the eventBusURL into one parameter

I was thinking that hypothetically purely theoretically in a future far far away in a huge cluster of many Minecraft sub server nodes perhaps the static JS app content would also be exposed on an external  CDN after all, while the EventBus would be on a different URL, so it couldn't hurt to keep them separate - even though, in the short term, they will typically both have the same base hostname (but not port and URL).

**Comment by edewit** [comment]
right makes sense, let's keep them separate for now
