### ISSUE TITLE
RFE: Inspiration from world edit to select coordinates for When Inside block

### ISSUE THREAD

**Issue by devvorb** [vorburger/minecraft-storeys-maker#7]
How about you use the wooden axe idea from worldedit(use another tool) to select an area for "when enter area block" instead of having to painfully get and copy 6 coordinates

**Comment by vorburger** [comment]
I just [stumbled over this interesting information here](https://minecraft.gamepedia.com/Multiplayer#Chat):

> Certain commands that handle blocks (/blockdata, /fill, etc.) have parameters that need the x, y, and z coordinates of the target block(s). Using the Tab ↹ key when these coordinates are needed will automatically add the coordinates of the block you are looking at.

and just wondering if it would make senes to leverage this, somehow... perhaps we could, in the future, have a command like `/block inside <x1 y1 z1 x2 y2 z2>` which "gives" (or just sets default parameters of?) a block in Scratch?

**Comment by edewit** [comment]
This is the [API](https://jd.spongepowered.org/5.0.0/org/spongepowered/api/command/spec/CommandSpec.html#getSuggestions-org.spongepowered.api.command.CommandSource-java.lang.String-org.spongepowered.api.world.Location-) to do that

**Comment by vorburger** [comment]
Closing this as #114 implemented this; differently than the idea outlined above - but even nicer!
