### ISSUE TITLE
Logo design proposal

### ISSUE THREAD

**Issue by teneresa** [vorburger/minecraft-storeys-maker#74]
Dear Sir/Madam, 
hi, my name is Valeria. I'm a graphic designer and I'd like to collaborate on your open source project and to propose free logo design. If it's something you're interested in, please, let me know!
Best,
Valeria

**Comment by vorburger** [comment]
@teneresa thank you for your kind offer. As an open community project, we welcome contributions.

A logo which combines Minecraft with themes of "learning programming" and has something reminding one of https://scratch.mit.edu - WITHOUT infringing on the Minecraft and Scratch logo copyrights (and that is the difficult part...) would certainly be welcome!

PS: You are probably doing this for https://join.utopian.io ? :smiley:   Cool!

**Comment by teneresa** [comment]
Thanks for your answer! I'm starting working on it and I'll share my ideas with you shortly. It's great that you know about Utopian! :) 
Best,
Valeria

**Comment by vorburger** [comment]
@teneresa can I just make sure that you understand that obviously we have $0 to compensate you? This is a purely volunteer driven project, and all contributions are for glory and fame, not money. I also need to sort out some sort of Contributor Agreement when I have time, to clarify contributing to this project.

@edewit FYI

**Comment by teneresa** [comment]
Yes, this is absolutely free for you! 
I'd like to clarify also how do you plan to use the logo - only for web or somewhere else? And if it requires an icon for Google Play store, etc. or not?

**Comment by vorburger** [comment]
@teneresa no mobile apps / Google | Apple Play store, no. Check out https://www.learn.study for what we actually do here... :smile: The logo could, for now, e.g. go there and on https://github.com/OASIS-learn-study as the logo for that GitHub org.

**Comment by teneresa** [comment]
Ahh.. I see, thank you! I will consider this in my design :)

**Comment by teneresa** [comment]
Dear Michael,
I checked all the information you provided and I need some clarifications if you don't mind. Could you, please, correct me if I'm wrong.
1. The logo has to contain the next text: The OASIS on learn.study
2. It has to be in a similar style to Minecraft - pixel art, geometric blocks, etc.?
3. It requires a cute character like the ones from Scratch.
4. It should be about learning programming.

Best,
Valeria

**Comment by vorburger** [comment]
@teneresa sounds great. The 1. text "... OASIS ..." is not important, don't put that as part of the logo.

Re. 3. cute character like the ones from Scratch, I just read this [on Scratch Terms of Use](https://scratch.mit.edu/terms_of_use) §5.4 :

> 5.4 The Scratch name, Scratch logo, Scratch Day logo, Scratch Cat, and Gobo are Trademarks owned by the Scratch Team. The MIT name and logo are Trademarks owned by the Massachusetts Institute of Technology. Unless you are licensed by Scratch under a specific licensing program or agreement, you may not use these logos to label, promote, or endorse any product or service. You may use the Scratch Logo to refer to the Scratch website and programming language.

So perhaps, if you can, it's best not to use that orange Scratch cat, but just some of those "blocks" (= "programming visually"). You can also look at https://developers.google.com/blockly/ for that. Perhaps something like that "[forever imagine program share](https://www.google.ch/search?safe=active&biw=955&bih=483&tbm=isch&sa=1&ei=yHIOW_-gEcf98QWW46i4DQ&q=scratch+forever+imagine+program+share)" kind of design.

**Comment by teneresa** [comment]
Hi Michael, thanks for your reply!
Could you please specify which text has to be included in the logo? Or it will be just a picture without any text?
As for the Scratch cat, I meant any other character - fox, owl, etc. drawn in a similar manner, if it's required :)

**Comment by vorburger** [comment]
No text at all is best I think, to be able to use it in different places.

**Comment by teneresa** [comment]
Ok, great! And the character?

**Comment by vorburger** [comment]
Re. the character, I'm not 100% sure but perhaps just "blocks" and no animal character at all? But you're the expert logo designer... perhaps if you wanted to illustrate sketches of several basic ideas, then we (me & @edewit) could give you feedback which one we felt best represented the project?

**Comment by teneresa** [comment]
Ok, I will try both options :)

**Comment by teneresa** [comment]
Hi Michael, I prepared a simple sketch just to illustrate some ideas. 
So, I used a cube as the Minecraft symbol and Scratch-blocks together as a base. The other objects - a laptop, a book and a graduation cap as symbols of study/learning. And a fox as a mascot. 
Please have a look and let me know if there is any good decision :)
![sketch](https://user-images.githubusercontent.com/39339824/40764301-e52656da-647e-11e8-9e53-1a5674cbcc65.jpg)

**Comment by edewit** [comment]
@teneresa really nice I like how you where able to combine everything. My personal favorite is 6 because it has a flow idea and a general idea of how it all works. 1, 2 and 3 are also nice, but 4 and 5 are just a bit to much I think.

**Comment by teneresa** [comment]
Hi Erik, thanks for your kind opinion! I will prepare some options for the 6th and share them here. 
Michael, do you agree with 6th as well?

**Comment by vorburger** [comment]
Valeria, wow cool! My favorite is #1 or else also #6. But I fear 6 with the 2 blocks is harder to put into a small logo, such as the GitHub Org on https://github.com/OASIS-learn-study, or on the Minecraft server list where this could be cool... although at max 64x64 that may be challenging either way? See also e.g. https://minecraft-logo-maker.com/ BTW many sites such as https://mc-servers.com and https://Minecraftserverlist.com or http://www.minecraft-servers-list.org and others like that seem to use "banners" - may be a possible future variation to also keep in mind here?

**Comment by teneresa** [comment]
Michael, Erik, hi, 
I made some examples, they are not final versions, just an experiment with forms and colors. 
What do you think? 
![logo v 01](https://user-images.githubusercontent.com/39339824/40870078-e9cffdbe-65fd-11e8-8efa-c7b4faaa1509.jpg)

**Comment by vorburger** [comment]
Valeria, you are great! I just showed this to my children for the first time, without context / telling yet what it was about, and was surprised that they immediately recognized Minecraft and Scratch! So we're on the right track here... ;) 

They (and I!) like something along the lines of the last row best. I was wondering if it made any sense to try if the Scratch blocks could "stand up" (out) on top of the Minecraft block? In the first row with the 2 blocks, there is (visually) "too much", for me - @edewit what do you think? In the second row it says too much "browser" (tab) - if it showed no browser frame and tab and only a Minecraft block and Scratch blocks next to each other somehow, then it could also work for me - but that then makes it closer to the last row.

**Comment by teneresa** [comment]
Michael, thanks for your feedback! I made some more options, please have a look. The 1st and the 2nd are more symbolic and maybe more suitable for logo. The 3d and the 4th are isometric and volume, and we can play with their "roof" and "walls" :)
![logo v2-01](https://user-images.githubusercontent.com/39339824/40882494-f2a24912-66b9-11e8-9ac9-6b71d85f7168.jpg)

**Comment by vorburger** [comment]
Valeria, minor misunderstanding perhaps, I think - by 'if the Scratch blocks could "stand up" (out) on top of' I meant to see how it would look if the (original) 3rd row block had on top of it the Scratch blocks as in the (original) 2nd row, without "browser" (tab), but standing "verticallyr" (?) in the air not "flat" (not as a "hovering roof") - do you know what I mean? 

I do also like the 3. and 4. (not so much 1. and 2.), so the above is just ot see how it would compare. BTW those "legs" in 4. IMHO do not remind of Minecraft as much as the "full" block in which works better. I'm undecided re. the "overlapping" in 3. vs 4.

**Comment by teneresa** [comment]
Hi Michael, and thank you for your comment! Yes, I understood what you meant (I hope so :), please have a look at numbers 5 and 6. And the others as well, just to compare. 
What do you think?
![logo v3-01](https://user-images.githubusercontent.com/39339824/40887505-345e2ad6-6720-11e8-8f8a-d1d6207576aa.jpg)
As for the colors, it is customary to do both options - mono and multicolor, so you'll be able to use both :)

**Comment by vorburger** [comment]
I guess one drawback of 5 VS 1/2 is that it's not (64x64) square...

**Comment by teneresa** [comment]
Michael, I made some options based on your last comment, please have a look.
![logo v4-01](https://user-images.githubusercontent.com/39339824/40895680-29d72506-6787-11e8-8035-18f2b2374773.jpg)

**Comment by edewit** [comment]
@teneresa super cool, I liked the sketch  of 6 but in color I like it less. Love these last ones, one and two are really great. Would it be an option to make the "Scratch" part yellow?

**Comment by vorburger** [comment]
I also do like 1/2 here very much! If I had to find 1 thing to nit pick I would say I now miss the round "hat block" on top... sorry! :smiley: Even 3/4 actually aren't bad at all.. the vote in my family was a tie! Finding it hard to choose, but perhaps I do have like a slight preference for 1/2 over 3/4 - you @edewit ? And @teneresa yourself?? You are the expert for "what works" in logo matters.

@edewit that earlier 6. would be fine with me, but (1) on lower res that non-frontal slightly turned Scratch may come out less ideal / grainy and (2) harder to fit 6 into a square like Minecraft server list and such?

Now 1/2 VS 3/4 really only differ in shading... So if the next step here is turning to colours: I do like colorful! :smile: Why not throw in all of the typical Scratch colours on the Scratch blocks - is that too much? And the usual Minecraft green grass / brown dirt onto the Minecraft block?

**Comment by teneresa** [comment]
Erik, thank you very much! I think that both color schemes are suitable to be used on your web pages or somewhere else on the internet. It depends on what you'd like to stress more on your project - Scratch or Minecraft. Michael, and what do you think?

**Comment by edewit** [comment]
@vorburger ping!?

**Comment by vorburger** [comment]
@teneresa so sorry for the delay, was caught up in what I do for work, which is not this project... ;-)

So @edewit and I sync'd up and we choose 2b! Wow. We have a "real" (professional!) logo...

**Comment by teneresa** [comment]
Michael, glad to hear from you again! I prepared all the files and created a pull-request. Please, check it and merge if everything is Ok.

**Comment by vorburger** [comment]
@teneresa you're perhaps more skilled to make the 64x64 variant look less "smooshy" (grainy) ?

> how I can get it onto the Minecraft client server list GUI

We just need to put a 64x64 PNG named (exactly) `server-logo.png` next to the `server.properties` ...

Oh, and [I'll make it](https://www.favicon-generator.org) a [Favicon](https://en.wikipedia.org/wiki/Favicon) also! ;) Then I'm going to the pool.

**Comment by vorburger** [comment]
> Oh, and I'll make it a Favicon also! ;)

https://github.com/OASIS-learn-study/oasis.learn.study/commit/04685616d8db44f84ec6a6ec3f1e0c57739c6fe8

> put a 64x64 PNG named (exactly) server-logo.png

https://github.com/OASIS-learn-study/swissarmyknife-minecraft-server/commit/5b6b995dbe6a223948d960d5ec4f17a9c9f10286

![minecraft 1 12 2_011](https://user-images.githubusercontent.com/298598/41191960-7948aece-6bf7-11e8-8e32-839cf3cc2a4f.png)

**Comment by teneresa** [comment]
Michael, hi! As for the server logo 64x64, the one I see in your logo folder looks good and no smooshy :) Do you want me to improve it? Or perhaps you can use an SVG file, I can prepare it as well.

**Comment by teneresa** [comment]
Michael, I added a folder 64x64 to my Google drive, [here](https://drive.google.com/open?id=10EF6-nVg2Ry8nqELRlhM9ssfG-O0Ewhf) is a link. You can find the required png and SVG files in it.

**Comment by teneresa** [comment]
Michael, thanks for your kind words! If you want, you can mention my nic teneresa somewhere where it's reasonable. It would be nice :)
And yes, we can close the issue!

**Comment by vorburger** [comment]
> yu can mention my nic teneresa somewhere where it's reasonable. It would be nice :)

https://twitter.com/vorburger/status/1006658533465772034 ;-)

PS: Perhaps you would like to set up https://twitter.com/teneresa ?

**Comment by vorburger** [comment]
and also https://twitter.com/edewit/status/1006502251010121728

**Comment by teneresa** [comment]
Ou, thank you very much! It's so nice :) Hope this new logo will bring good luck to the project!
I have a page on twitter: https://twitter.com/Teneressa
But anyway thanks again for your kind words!
